version: 2

jobs:
    examples:
        docker:
          - image: circleci/python:3.8
        steps:
          - checkout
          - run: |
              pip install -r requirements.txt
              for f in examples/wipac_tracing/*.py; do python "$f"; done

workflows:
    version: 2
    build_and_test:
        jobs:
            - examples
