version: 2

jobs:
    examples:
        docker:
          - image: circleci/python:3.8
          - image: deadtrickster/rabbitmq_prometheus:3.7
          - image: otel/opentelemetry-collector:latest
        steps:
          - checkout
          - run: dockerize -wait tcp://localhost:5672 -timeout 1m
          - run: |
              pip install -r requirements.txt
              pip install pika
              ./examples/wipac_tracing/run_all_examples.sh

workflows:
    version: 2
    build_and_test:
        jobs:
            - examples
