version: 2

jobs:
    examples:
        docker:
          - image: circleci/python:3.8
        steps:
          - checkout
          - run: |
              pip install -r requirements.txt
              ./examples/wipac_tracing/run_all_examples.sh

workflows:
    version: 2
    build_and_test:
        jobs:
            - examples
