name: Try Setup Install

on: [push]

jobs:
  try-setup-install:
    runs-on: ubuntu-latest

    container:
      image: docker/python:3.8.3

    steps:
    - name: Checkout Branch
      uses: actions/checkout@v2

    - name: Execute
      run: |
        python3 -m virtualenv -p python3 env
        . env/bin/activate
        python setup.py install
